// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/CanalProtocol.proto

package com_alibaba_otter_canal_protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Compression int32

const (
	Compression_COMPRESSIONCOMPATIBLEPROTO2 Compression = 0
	Compression_NONE                        Compression = 1
	Compression_ZLIB                        Compression = 2
	Compression_GZIP                        Compression = 3
	Compression_LZF                         Compression = 4
)

var Compression_name = map[int32]string{
	0: "COMPRESSIONCOMPATIBLEPROTO2",
	1: "NONE",
	2: "ZLIB",
	3: "GZIP",
	4: "LZF",
}
var Compression_value = map[string]int32{
	"COMPRESSIONCOMPATIBLEPROTO2": 0,
	"NONE": 1,
	"ZLIB": 2,
	"GZIP": 3,
	"LZF":  4,
}

func (x Compression) String() string {
	return proto.EnumName(Compression_name, int32(x))
}
func (Compression) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{0}
}

type PacketType int32

const (
	// compatible
	PacketType_PACKAGETYPECOMPATIBLEPROTO2 PacketType = 0
	PacketType_HANDSHAKE                   PacketType = 1
	PacketType_CLIENTAUTHENTICATION        PacketType = 2
	PacketType_ACK                         PacketType = 3
	PacketType_SUBSCRIPTION                PacketType = 4
	PacketType_UNSUBSCRIPTION              PacketType = 5
	PacketType_GET                         PacketType = 6
	PacketType_MESSAGES                    PacketType = 7
	PacketType_CLIENTACK                   PacketType = 8
	// management part
	PacketType_SHUTDOWN PacketType = 9
	// integration
	PacketType_DUMP           PacketType = 10
	PacketType_HEARTBEAT      PacketType = 11
	PacketType_CLIENTROLLBACK PacketType = 12
)

var PacketType_name = map[int32]string{
	0:  "PACKAGETYPECOMPATIBLEPROTO2",
	1:  "HANDSHAKE",
	2:  "CLIENTAUTHENTICATION",
	3:  "ACK",
	4:  "SUBSCRIPTION",
	5:  "UNSUBSCRIPTION",
	6:  "GET",
	7:  "MESSAGES",
	8:  "CLIENTACK",
	9:  "SHUTDOWN",
	10: "DUMP",
	11: "HEARTBEAT",
	12: "CLIENTROLLBACK",
}
var PacketType_value = map[string]int32{
	"PACKAGETYPECOMPATIBLEPROTO2": 0,
	"HANDSHAKE":                   1,
	"CLIENTAUTHENTICATION":        2,
	"ACK":            3,
	"SUBSCRIPTION":   4,
	"UNSUBSCRIPTION": 5,
	"GET":            6,
	"MESSAGES":       7,
	"CLIENTACK":      8,
	"SHUTDOWN":       9,
	"DUMP":           10,
	"HEARTBEAT":      11,
	"CLIENTROLLBACK": 12,
}

func (x PacketType) String() string {
	return proto.EnumName(PacketType_name, int32(x))
}
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{1}
}

type Packet struct {
	// [default = 17];
	//
	// Types that are valid to be assigned to MagicNumberPresent:
	//	*Packet_MagicNumber
	MagicNumberPresent isPacket_MagicNumberPresent `protobuf_oneof:"magic_number_present"`
	// [default = 1];
	//
	// Types that are valid to be assigned to VersionPresent:
	//	*Packet_Version
	VersionPresent isPacket_VersionPresent `protobuf_oneof:"version_present"`
	Type           PacketType              `protobuf:"varint,3,opt,name=type,proto3,enum=com.alibaba.otter.canal.protocol.PacketType" json:"type,omitempty"`
	// [default = NONE];
	//
	// Types that are valid to be assigned to CompressionPresent:
	//	*Packet_Compression
	CompressionPresent   isPacket_CompressionPresent `protobuf_oneof:"compression_present"`
	Body                 []byte                      `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{0}
}
func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (dst *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(dst, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

type isPacket_MagicNumberPresent interface {
	isPacket_MagicNumberPresent()
}

type Packet_MagicNumber struct {
	MagicNumber int32 `protobuf:"varint,1,opt,name=magic_number,json=magicNumber,proto3,oneof"`
}

func (*Packet_MagicNumber) isPacket_MagicNumberPresent() {}

func (m *Packet) GetMagicNumberPresent() isPacket_MagicNumberPresent {
	if m != nil {
		return m.MagicNumberPresent
	}
	return nil
}

func (m *Packet) GetMagicNumber() int32 {
	if x, ok := m.GetMagicNumberPresent().(*Packet_MagicNumber); ok {
		return x.MagicNumber
	}
	return 0
}

type isPacket_VersionPresent interface {
	isPacket_VersionPresent()
}

type Packet_Version struct {
	Version int32 `protobuf:"varint,2,opt,name=version,proto3,oneof"`
}

func (*Packet_Version) isPacket_VersionPresent() {}

func (m *Packet) GetVersionPresent() isPacket_VersionPresent {
	if m != nil {
		return m.VersionPresent
	}
	return nil
}

func (m *Packet) GetVersion() int32 {
	if x, ok := m.GetVersionPresent().(*Packet_Version); ok {
		return x.Version
	}
	return 0
}

func (m *Packet) GetType() PacketType {
	if m != nil {
		return m.Type
	}
	return PacketType_PACKAGETYPECOMPATIBLEPROTO2
}

type isPacket_CompressionPresent interface {
	isPacket_CompressionPresent()
}

type Packet_Compression struct {
	Compression Compression `protobuf:"varint,4,opt,name=compression,proto3,enum=com.alibaba.otter.canal.protocol.Compression,oneof"`
}

func (*Packet_Compression) isPacket_CompressionPresent() {}

func (m *Packet) GetCompressionPresent() isPacket_CompressionPresent {
	if m != nil {
		return m.CompressionPresent
	}
	return nil
}

func (m *Packet) GetCompression() Compression {
	if x, ok := m.GetCompressionPresent().(*Packet_Compression); ok {
		return x.Compression
	}
	return Compression_COMPRESSIONCOMPATIBLEPROTO2
}

func (m *Packet) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Packet) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Packet_OneofMarshaler, _Packet_OneofUnmarshaler, _Packet_OneofSizer, []interface{}{
		(*Packet_MagicNumber)(nil),
		(*Packet_Version)(nil),
		(*Packet_Compression)(nil),
	}
}

func _Packet_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Packet)
	// magic_number_present
	switch x := m.MagicNumberPresent.(type) {
	case *Packet_MagicNumber:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.MagicNumber))
	case nil:
	default:
		return fmt.Errorf("Packet.MagicNumberPresent has unexpected type %T", x)
	}
	// version_present
	switch x := m.VersionPresent.(type) {
	case *Packet_Version:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Version))
	case nil:
	default:
		return fmt.Errorf("Packet.VersionPresent has unexpected type %T", x)
	}
	// compression_present
	switch x := m.CompressionPresent.(type) {
	case *Packet_Compression:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Compression))
	case nil:
	default:
		return fmt.Errorf("Packet.CompressionPresent has unexpected type %T", x)
	}
	return nil
}

func _Packet_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Packet)
	switch tag {
	case 1: // magic_number_present.magic_number
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.MagicNumberPresent = &Packet_MagicNumber{int32(x)}
		return true, err
	case 2: // version_present.version
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.VersionPresent = &Packet_Version{int32(x)}
		return true, err
	case 4: // compression_present.compression
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.CompressionPresent = &Packet_Compression{Compression(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Packet_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Packet)
	// magic_number_present
	switch x := m.MagicNumberPresent.(type) {
	case *Packet_MagicNumber:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.MagicNumber))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// version_present
	switch x := m.VersionPresent.(type) {
	case *Packet_Version:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Version))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// compression_present
	switch x := m.CompressionPresent.(type) {
	case *Packet_Compression:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Compression))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HeartBeat struct {
	SendTimestamp        int64    `protobuf:"varint,1,opt,name=send_timestamp,json=sendTimestamp,proto3" json:"send_timestamp,omitempty"`
	StartTimestamp       int64    `protobuf:"varint,2,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{1}
}
func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (dst *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(dst, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func (m *HeartBeat) GetSendTimestamp() int64 {
	if m != nil {
		return m.SendTimestamp
	}
	return 0
}

func (m *HeartBeat) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

type Handshake struct {
	//  [default = "utf8"];
	//
	// Types that are valid to be assigned to CommunicationEncodingPresent:
	//	*Handshake_CommunicationEncoding
	CommunicationEncodingPresent isHandshake_CommunicationEncodingPresent `protobuf_oneof:"communication_encoding_present"`
	Seeds                        []byte                                   `protobuf:"bytes,2,opt,name=seeds,proto3" json:"seeds,omitempty"`
	SupportedCompressions        Compression                              `protobuf:"varint,3,opt,name=supported_compressions,json=supportedCompressions,proto3,enum=com.alibaba.otter.canal.protocol.Compression" json:"supported_compressions,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                                 `json:"-"`
	XXX_unrecognized             []byte                                   `json:"-"`
	XXX_sizecache                int32                                    `json:"-"`
}

func (m *Handshake) Reset()         { *m = Handshake{} }
func (m *Handshake) String() string { return proto.CompactTextString(m) }
func (*Handshake) ProtoMessage()    {}
func (*Handshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{2}
}
func (m *Handshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handshake.Unmarshal(m, b)
}
func (m *Handshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handshake.Marshal(b, m, deterministic)
}
func (dst *Handshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handshake.Merge(dst, src)
}
func (m *Handshake) XXX_Size() int {
	return xxx_messageInfo_Handshake.Size(m)
}
func (m *Handshake) XXX_DiscardUnknown() {
	xxx_messageInfo_Handshake.DiscardUnknown(m)
}

var xxx_messageInfo_Handshake proto.InternalMessageInfo

type isHandshake_CommunicationEncodingPresent interface {
	isHandshake_CommunicationEncodingPresent()
}

type Handshake_CommunicationEncoding struct {
	CommunicationEncoding string `protobuf:"bytes,1,opt,name=communication_encoding,json=communicationEncoding,proto3,oneof"`
}

func (*Handshake_CommunicationEncoding) isHandshake_CommunicationEncodingPresent() {}

func (m *Handshake) GetCommunicationEncodingPresent() isHandshake_CommunicationEncodingPresent {
	if m != nil {
		return m.CommunicationEncodingPresent
	}
	return nil
}

func (m *Handshake) GetCommunicationEncoding() string {
	if x, ok := m.GetCommunicationEncodingPresent().(*Handshake_CommunicationEncoding); ok {
		return x.CommunicationEncoding
	}
	return ""
}

func (m *Handshake) GetSeeds() []byte {
	if m != nil {
		return m.Seeds
	}
	return nil
}

func (m *Handshake) GetSupportedCompressions() Compression {
	if m != nil {
		return m.SupportedCompressions
	}
	return Compression_COMPRESSIONCOMPATIBLEPROTO2
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Handshake) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Handshake_OneofMarshaler, _Handshake_OneofUnmarshaler, _Handshake_OneofSizer, []interface{}{
		(*Handshake_CommunicationEncoding)(nil),
	}
}

func _Handshake_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Handshake)
	// communication_encoding_present
	switch x := m.CommunicationEncodingPresent.(type) {
	case *Handshake_CommunicationEncoding:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.CommunicationEncoding)
	case nil:
	default:
		return fmt.Errorf("Handshake.CommunicationEncodingPresent has unexpected type %T", x)
	}
	return nil
}

func _Handshake_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Handshake)
	switch tag {
	case 1: // communication_encoding_present.communication_encoding
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.CommunicationEncodingPresent = &Handshake_CommunicationEncoding{x}
		return true, err
	default:
		return false, nil
	}
}

func _Handshake_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Handshake)
	// communication_encoding_present
	switch x := m.CommunicationEncodingPresent.(type) {
	case *Handshake_CommunicationEncoding:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CommunicationEncoding)))
		n += len(x.CommunicationEncoding)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// client authentication
type ClientAuth struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// [default = 0]
	//
	// Types that are valid to be assigned to NetReadTimeoutPresent:
	//	*ClientAuth_NetReadTimeout
	NetReadTimeoutPresent isClientAuth_NetReadTimeoutPresent `protobuf_oneof:"net_read_timeout_present"`
	// [default = 0];
	//
	// Types that are valid to be assigned to NetWriteTimeoutPresent:
	//	*ClientAuth_NetWriteTimeout
	NetWriteTimeoutPresent isClientAuth_NetWriteTimeoutPresent `protobuf_oneof:"net_write_timeout_present"`
	Destination            string                              `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	ClientId               string                              `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Filter                 string                              `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	StartTimestamp         int64                               `protobuf:"varint,8,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                            `json:"-"`
	XXX_unrecognized       []byte                              `json:"-"`
	XXX_sizecache          int32                               `json:"-"`
}

func (m *ClientAuth) Reset()         { *m = ClientAuth{} }
func (m *ClientAuth) String() string { return proto.CompactTextString(m) }
func (*ClientAuth) ProtoMessage()    {}
func (*ClientAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{3}
}
func (m *ClientAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientAuth.Unmarshal(m, b)
}
func (m *ClientAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientAuth.Marshal(b, m, deterministic)
}
func (dst *ClientAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAuth.Merge(dst, src)
}
func (m *ClientAuth) XXX_Size() int {
	return xxx_messageInfo_ClientAuth.Size(m)
}
func (m *ClientAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAuth.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAuth proto.InternalMessageInfo

func (m *ClientAuth) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ClientAuth) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type isClientAuth_NetReadTimeoutPresent interface {
	isClientAuth_NetReadTimeoutPresent()
}

type ClientAuth_NetReadTimeout struct {
	NetReadTimeout int32 `protobuf:"varint,3,opt,name=net_read_timeout,json=netReadTimeout,proto3,oneof"`
}

func (*ClientAuth_NetReadTimeout) isClientAuth_NetReadTimeoutPresent() {}

func (m *ClientAuth) GetNetReadTimeoutPresent() isClientAuth_NetReadTimeoutPresent {
	if m != nil {
		return m.NetReadTimeoutPresent
	}
	return nil
}

func (m *ClientAuth) GetNetReadTimeout() int32 {
	if x, ok := m.GetNetReadTimeoutPresent().(*ClientAuth_NetReadTimeout); ok {
		return x.NetReadTimeout
	}
	return 0
}

type isClientAuth_NetWriteTimeoutPresent interface {
	isClientAuth_NetWriteTimeoutPresent()
}

type ClientAuth_NetWriteTimeout struct {
	NetWriteTimeout int32 `protobuf:"varint,4,opt,name=net_write_timeout,json=netWriteTimeout,proto3,oneof"`
}

func (*ClientAuth_NetWriteTimeout) isClientAuth_NetWriteTimeoutPresent() {}

func (m *ClientAuth) GetNetWriteTimeoutPresent() isClientAuth_NetWriteTimeoutPresent {
	if m != nil {
		return m.NetWriteTimeoutPresent
	}
	return nil
}

func (m *ClientAuth) GetNetWriteTimeout() int32 {
	if x, ok := m.GetNetWriteTimeoutPresent().(*ClientAuth_NetWriteTimeout); ok {
		return x.NetWriteTimeout
	}
	return 0
}

func (m *ClientAuth) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *ClientAuth) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ClientAuth) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ClientAuth) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientAuth) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientAuth_OneofMarshaler, _ClientAuth_OneofUnmarshaler, _ClientAuth_OneofSizer, []interface{}{
		(*ClientAuth_NetReadTimeout)(nil),
		(*ClientAuth_NetWriteTimeout)(nil),
	}
}

func _ClientAuth_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientAuth)
	// net_read_timeout_present
	switch x := m.NetReadTimeoutPresent.(type) {
	case *ClientAuth_NetReadTimeout:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.NetReadTimeout))
	case nil:
	default:
		return fmt.Errorf("ClientAuth.NetReadTimeoutPresent has unexpected type %T", x)
	}
	// net_write_timeout_present
	switch x := m.NetWriteTimeoutPresent.(type) {
	case *ClientAuth_NetWriteTimeout:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.NetWriteTimeout))
	case nil:
	default:
		return fmt.Errorf("ClientAuth.NetWriteTimeoutPresent has unexpected type %T", x)
	}
	return nil
}

func _ClientAuth_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientAuth)
	switch tag {
	case 3: // net_read_timeout_present.net_read_timeout
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.NetReadTimeoutPresent = &ClientAuth_NetReadTimeout{int32(x)}
		return true, err
	case 4: // net_write_timeout_present.net_write_timeout
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.NetWriteTimeoutPresent = &ClientAuth_NetWriteTimeout{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _ClientAuth_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientAuth)
	// net_read_timeout_present
	switch x := m.NetReadTimeoutPresent.(type) {
	case *ClientAuth_NetReadTimeout:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.NetReadTimeout))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// net_write_timeout_present
	switch x := m.NetWriteTimeoutPresent.(type) {
	case *ClientAuth_NetWriteTimeout:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.NetWriteTimeout))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Ack struct {
	// [default = 0]
	//
	// Types that are valid to be assigned to ErrorCodePresent:
	//	*Ack_ErrorCode
	ErrorCodePresent     isAck_ErrorCodePresent `protobuf_oneof:"error_code_present"`
	ErrorMessage         string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{4}
}
func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (dst *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(dst, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

type isAck_ErrorCodePresent interface {
	isAck_ErrorCodePresent()
}

type Ack_ErrorCode struct {
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,oneof"`
}

func (*Ack_ErrorCode) isAck_ErrorCodePresent() {}

func (m *Ack) GetErrorCodePresent() isAck_ErrorCodePresent {
	if m != nil {
		return m.ErrorCodePresent
	}
	return nil
}

func (m *Ack) GetErrorCode() int32 {
	if x, ok := m.GetErrorCodePresent().(*Ack_ErrorCode); ok {
		return x.ErrorCode
	}
	return 0
}

func (m *Ack) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Ack) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Ack_OneofMarshaler, _Ack_OneofUnmarshaler, _Ack_OneofSizer, []interface{}{
		(*Ack_ErrorCode)(nil),
	}
}

func _Ack_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Ack)
	// error_code_present
	switch x := m.ErrorCodePresent.(type) {
	case *Ack_ErrorCode:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.ErrorCode))
	case nil:
	default:
		return fmt.Errorf("Ack.ErrorCodePresent has unexpected type %T", x)
	}
	return nil
}

func _Ack_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Ack)
	switch tag {
	case 1: // error_code_present.error_code
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.ErrorCodePresent = &Ack_ErrorCode{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Ack_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Ack)
	// error_code_present
	switch x := m.ErrorCodePresent.(type) {
	case *Ack_ErrorCode:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.ErrorCode))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ClientAck struct {
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BatchId              int64    `protobuf:"varint,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientAck) Reset()         { *m = ClientAck{} }
func (m *ClientAck) String() string { return proto.CompactTextString(m) }
func (*ClientAck) ProtoMessage()    {}
func (*ClientAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{5}
}
func (m *ClientAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientAck.Unmarshal(m, b)
}
func (m *ClientAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientAck.Marshal(b, m, deterministic)
}
func (dst *ClientAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientAck.Merge(dst, src)
}
func (m *ClientAck) XXX_Size() int {
	return xxx_messageInfo_ClientAck.Size(m)
}
func (m *ClientAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientAck.DiscardUnknown(m)
}

var xxx_messageInfo_ClientAck proto.InternalMessageInfo

func (m *ClientAck) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *ClientAck) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ClientAck) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

// subscription
type Sub struct {
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Filter               string   `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sub) Reset()         { *m = Sub{} }
func (m *Sub) String() string { return proto.CompactTextString(m) }
func (*Sub) ProtoMessage()    {}
func (*Sub) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{6}
}
func (m *Sub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sub.Unmarshal(m, b)
}
func (m *Sub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sub.Marshal(b, m, deterministic)
}
func (dst *Sub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sub.Merge(dst, src)
}
func (m *Sub) XXX_Size() int {
	return xxx_messageInfo_Sub.Size(m)
}
func (m *Sub) XXX_DiscardUnknown() {
	xxx_messageInfo_Sub.DiscardUnknown(m)
}

var xxx_messageInfo_Sub proto.InternalMessageInfo

func (m *Sub) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Sub) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Sub) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

// Unsubscription
type Unsub struct {
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Filter               string   `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unsub) Reset()         { *m = Unsub{} }
func (m *Unsub) String() string { return proto.CompactTextString(m) }
func (*Unsub) ProtoMessage()    {}
func (*Unsub) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{7}
}
func (m *Unsub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unsub.Unmarshal(m, b)
}
func (m *Unsub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unsub.Marshal(b, m, deterministic)
}
func (dst *Unsub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unsub.Merge(dst, src)
}
func (m *Unsub) XXX_Size() int {
	return xxx_messageInfo_Unsub.Size(m)
}
func (m *Unsub) XXX_DiscardUnknown() {
	xxx_messageInfo_Unsub.DiscardUnknown(m)
}

var xxx_messageInfo_Unsub proto.InternalMessageInfo

func (m *Unsub) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Unsub) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Unsub) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

//  PullRequest
type Get struct {
	Destination string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ClientId    string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FetchSize   int32  `protobuf:"varint,3,opt,name=fetch_size,json=fetchSize,proto3" json:"fetch_size,omitempty"`
	// [default = -1]
	//
	// Types that are valid to be assigned to TimeoutPresent:
	//	*Get_Timeout
	TimeoutPresent isGet_TimeoutPresent `protobuf_oneof:"timeout_present"`
	// [default = 2]
	//
	// Types that are valid to be assigned to UnitPresent:
	//	*Get_Unit
	UnitPresent isGet_UnitPresent `protobuf_oneof:"unit_present"`
	// [default = false]
	//
	// Types that are valid to be assigned to AutoAckPresent:
	//	*Get_AutoAck
	AutoAckPresent       isGet_AutoAckPresent `protobuf_oneof:"auto_ack_present"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Get) Reset()         { *m = Get{} }
func (m *Get) String() string { return proto.CompactTextString(m) }
func (*Get) ProtoMessage()    {}
func (*Get) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{8}
}
func (m *Get) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Get.Unmarshal(m, b)
}
func (m *Get) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Get.Marshal(b, m, deterministic)
}
func (dst *Get) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Get.Merge(dst, src)
}
func (m *Get) XXX_Size() int {
	return xxx_messageInfo_Get.Size(m)
}
func (m *Get) XXX_DiscardUnknown() {
	xxx_messageInfo_Get.DiscardUnknown(m)
}

var xxx_messageInfo_Get proto.InternalMessageInfo

func (m *Get) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Get) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Get) GetFetchSize() int32 {
	if m != nil {
		return m.FetchSize
	}
	return 0
}

type isGet_TimeoutPresent interface {
	isGet_TimeoutPresent()
}

type Get_Timeout struct {
	Timeout int64 `protobuf:"varint,4,opt,name=timeout,proto3,oneof"`
}

func (*Get_Timeout) isGet_TimeoutPresent() {}

func (m *Get) GetTimeoutPresent() isGet_TimeoutPresent {
	if m != nil {
		return m.TimeoutPresent
	}
	return nil
}

func (m *Get) GetTimeout() int64 {
	if x, ok := m.GetTimeoutPresent().(*Get_Timeout); ok {
		return x.Timeout
	}
	return 0
}

type isGet_UnitPresent interface {
	isGet_UnitPresent()
}

type Get_Unit struct {
	Unit int32 `protobuf:"varint,5,opt,name=unit,proto3,oneof"`
}

func (*Get_Unit) isGet_UnitPresent() {}

func (m *Get) GetUnitPresent() isGet_UnitPresent {
	if m != nil {
		return m.UnitPresent
	}
	return nil
}

func (m *Get) GetUnit() int32 {
	if x, ok := m.GetUnitPresent().(*Get_Unit); ok {
		return x.Unit
	}
	return 0
}

type isGet_AutoAckPresent interface {
	isGet_AutoAckPresent()
}

type Get_AutoAck struct {
	AutoAck bool `protobuf:"varint,6,opt,name=auto_ack,json=autoAck,proto3,oneof"`
}

func (*Get_AutoAck) isGet_AutoAckPresent() {}

func (m *Get) GetAutoAckPresent() isGet_AutoAckPresent {
	if m != nil {
		return m.AutoAckPresent
	}
	return nil
}

func (m *Get) GetAutoAck() bool {
	if x, ok := m.GetAutoAckPresent().(*Get_AutoAck); ok {
		return x.AutoAck
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Get) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Get_OneofMarshaler, _Get_OneofUnmarshaler, _Get_OneofSizer, []interface{}{
		(*Get_Timeout)(nil),
		(*Get_Unit)(nil),
		(*Get_AutoAck)(nil),
	}
}

func _Get_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Get)
	// timeout_present
	switch x := m.TimeoutPresent.(type) {
	case *Get_Timeout:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Timeout))
	case nil:
	default:
		return fmt.Errorf("Get.TimeoutPresent has unexpected type %T", x)
	}
	// unit_present
	switch x := m.UnitPresent.(type) {
	case *Get_Unit:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Unit))
	case nil:
	default:
		return fmt.Errorf("Get.UnitPresent has unexpected type %T", x)
	}
	// auto_ack_present
	switch x := m.AutoAckPresent.(type) {
	case *Get_AutoAck:
		t := uint64(0)
		if x.AutoAck {
			t = 1
		}
		b.EncodeVarint(6<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("Get.AutoAckPresent has unexpected type %T", x)
	}
	return nil
}

func _Get_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Get)
	switch tag {
	case 4: // timeout_present.timeout
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TimeoutPresent = &Get_Timeout{int64(x)}
		return true, err
	case 5: // unit_present.unit
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.UnitPresent = &Get_Unit{int32(x)}
		return true, err
	case 6: // auto_ack_present.auto_ack
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.AutoAckPresent = &Get_AutoAck{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _Get_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Get)
	// timeout_present
	switch x := m.TimeoutPresent.(type) {
	case *Get_Timeout:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Timeout))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// unit_present
	switch x := m.UnitPresent.(type) {
	case *Get_Unit:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Unit))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	// auto_ack_present
	switch x := m.AutoAckPresent.(type) {
	case *Get_AutoAck:
		n += 1 // tag and wire
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

//
type Messages struct {
	BatchId              int64    `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Messages             [][]byte `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{9}
}
func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (dst *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(dst, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func (m *Messages) GetMessages() [][]byte {
	if m != nil {
		return m.Messages
	}
	return nil
}

// TBD when new packets are required
type Dump struct {
	Journal  string `protobuf:"bytes,1,opt,name=journal,proto3" json:"journal,omitempty"`
	Position int64  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	// [default = 0]
	//
	// Types that are valid to be assigned to TimestampPresent:
	//	*Dump_Timestamp
	TimestampPresent     isDump_TimestampPresent `protobuf_oneof:"timestamp_present"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Dump) Reset()         { *m = Dump{} }
func (m *Dump) String() string { return proto.CompactTextString(m) }
func (*Dump) ProtoMessage()    {}
func (*Dump) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{10}
}
func (m *Dump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dump.Unmarshal(m, b)
}
func (m *Dump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dump.Marshal(b, m, deterministic)
}
func (dst *Dump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dump.Merge(dst, src)
}
func (m *Dump) XXX_Size() int {
	return xxx_messageInfo_Dump.Size(m)
}
func (m *Dump) XXX_DiscardUnknown() {
	xxx_messageInfo_Dump.DiscardUnknown(m)
}

var xxx_messageInfo_Dump proto.InternalMessageInfo

func (m *Dump) GetJournal() string {
	if m != nil {
		return m.Journal
	}
	return ""
}

func (m *Dump) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

type isDump_TimestampPresent interface {
	isDump_TimestampPresent()
}

type Dump_Timestamp struct {
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3,oneof"`
}

func (*Dump_Timestamp) isDump_TimestampPresent() {}

func (m *Dump) GetTimestampPresent() isDump_TimestampPresent {
	if m != nil {
		return m.TimestampPresent
	}
	return nil
}

func (m *Dump) GetTimestamp() int64 {
	if x, ok := m.GetTimestampPresent().(*Dump_Timestamp); ok {
		return x.Timestamp
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Dump) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Dump_OneofMarshaler, _Dump_OneofUnmarshaler, _Dump_OneofSizer, []interface{}{
		(*Dump_Timestamp)(nil),
	}
}

func _Dump_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Dump)
	// timestamp_present
	switch x := m.TimestampPresent.(type) {
	case *Dump_Timestamp:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Timestamp))
	case nil:
	default:
		return fmt.Errorf("Dump.TimestampPresent has unexpected type %T", x)
	}
	return nil
}

func _Dump_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Dump)
	switch tag {
	case 3: // timestamp_present.timestamp
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TimestampPresent = &Dump_Timestamp{int64(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Dump_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Dump)
	// timestamp_present
	switch x := m.TimestampPresent.(type) {
	case *Dump_Timestamp:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Timestamp))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ClientRollback struct {
	Destination          string   `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	BatchId              int64    `protobuf:"varint,3,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRollback) Reset()         { *m = ClientRollback{} }
func (m *ClientRollback) String() string { return proto.CompactTextString(m) }
func (*ClientRollback) ProtoMessage()    {}
func (*ClientRollback) Descriptor() ([]byte, []int) {
	return fileDescriptor_CanalProtocol_d03a98cc6d8bdb99, []int{11}
}
func (m *ClientRollback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRollback.Unmarshal(m, b)
}
func (m *ClientRollback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRollback.Marshal(b, m, deterministic)
}
func (dst *ClientRollback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRollback.Merge(dst, src)
}
func (m *ClientRollback) XXX_Size() int {
	return xxx_messageInfo_ClientRollback.Size(m)
}
func (m *ClientRollback) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRollback.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRollback proto.InternalMessageInfo

func (m *ClientRollback) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *ClientRollback) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ClientRollback) GetBatchId() int64 {
	if m != nil {
		return m.BatchId
	}
	return 0
}

func init() {
	proto.RegisterType((*Packet)(nil), "com.alibaba.otter.canal.protocol.Packet")
	proto.RegisterType((*HeartBeat)(nil), "com.alibaba.otter.canal.protocol.HeartBeat")
	proto.RegisterType((*Handshake)(nil), "com.alibaba.otter.canal.protocol.Handshake")
	proto.RegisterType((*ClientAuth)(nil), "com.alibaba.otter.canal.protocol.ClientAuth")
	proto.RegisterType((*Ack)(nil), "com.alibaba.otter.canal.protocol.Ack")
	proto.RegisterType((*ClientAck)(nil), "com.alibaba.otter.canal.protocol.ClientAck")
	proto.RegisterType((*Sub)(nil), "com.alibaba.otter.canal.protocol.Sub")
	proto.RegisterType((*Unsub)(nil), "com.alibaba.otter.canal.protocol.Unsub")
	proto.RegisterType((*Get)(nil), "com.alibaba.otter.canal.protocol.Get")
	proto.RegisterType((*Messages)(nil), "com.alibaba.otter.canal.protocol.Messages")
	proto.RegisterType((*Dump)(nil), "com.alibaba.otter.canal.protocol.Dump")
	proto.RegisterType((*ClientRollback)(nil), "com.alibaba.otter.canal.protocol.ClientRollback")
	proto.RegisterEnum("com.alibaba.otter.canal.protocol.Compression", Compression_name, Compression_value)
	proto.RegisterEnum("com.alibaba.otter.canal.protocol.PacketType", PacketType_name, PacketType_value)
}

func init() {
	proto.RegisterFile("protocol/CanalProtocol.proto", fileDescriptor_CanalProtocol_d03a98cc6d8bdb99)
}

var fileDescriptor_CanalProtocol_d03a98cc6d8bdb99 = []byte{
	// 1017 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdf, 0x6e, 0xdb, 0xb6,
	0x17, 0x8e, 0x2c, 0x3b, 0xb6, 0x8e, 0x5d, 0x47, 0x61, 0x93, 0xc0, 0x4d, 0x7e, 0xbf, 0xd6, 0x70,
	0x31, 0x2c, 0x08, 0x3a, 0x0f, 0xeb, 0x2e, 0x76, 0x3b, 0x49, 0xd1, 0x22, 0x23, 0x8e, 0xed, 0x51,
	0x32, 0x8a, 0x65, 0xc3, 0x0c, 0x5a, 0x62, 0x13, 0xd5, 0x96, 0xe4, 0x89, 0xd4, 0x8a, 0xf4, 0xb9,
	0xf6, 0x2e, 0xbb, 0xdf, 0xc5, 0x80, 0xbd, 0xc5, 0x40, 0x4a, 0x56, 0x9c, 0x2c, 0x43, 0x30, 0x14,
	0xbd, 0xe3, 0xf9, 0xce, 0x3f, 0x9e, 0x8f, 0x1f, 0x29, 0xc1, 0xff, 0x56, 0x69, 0xc2, 0x13, 0x3f,
	0x59, 0x7e, 0x69, 0x91, 0x98, 0x2c, 0x27, 0x85, 0xd5, 0x97, 0x30, 0xea, 0xfa, 0x49, 0xd4, 0x27,
	0xcb, 0x70, 0x4e, 0xe6, 0xa4, 0x9f, 0x70, 0x4e, 0xd3, 0xbe, 0x2f, 0xc2, 0xfa, 0xeb, 0xac, 0xde,
	0x6f, 0x15, 0xd8, 0x9e, 0x10, 0x7f, 0x41, 0x39, 0x7a, 0x09, 0xad, 0x88, 0x5c, 0x85, 0xfe, 0x2c,
	0xce, 0xa2, 0x39, 0x4d, 0x3b, 0x4a, 0x57, 0x39, 0xae, 0x39, 0x5b, 0xb8, 0x29, 0xd1, 0x91, 0x04,
	0xd1, 0x21, 0xd4, 0x7f, 0xa5, 0x29, 0x0b, 0x93, 0xb8, 0x53, 0x91, 0x7e, 0x05, 0xaf, 0x01, 0xf4,
	0x2d, 0x54, 0xf9, 0xcd, 0x8a, 0x76, 0xd4, 0xae, 0x72, 0xdc, 0x7e, 0xfd, 0xaa, 0xff, 0x58, 0xf3,
	0x7e, 0xde, 0xd8, 0xbb, 0x59, 0x51, 0x2c, 0x33, 0xd1, 0xf7, 0xd0, 0xf4, 0x93, 0x68, 0x95, 0x52,
	0x26, 0x3b, 0x54, 0x65, 0xa1, 0x2f, 0x1e, 0x2f, 0x64, 0xdd, 0x26, 0x39, 0x15, 0xbc, 0x59, 0x03,
	0x21, 0xa8, 0xce, 0x93, 0xe0, 0xa6, 0x53, 0xeb, 0x2a, 0xc7, 0x2d, 0x2c, 0xd7, 0xe6, 0x01, 0xec,
	0x6d, 0x4e, 0x3a, 0x13, 0xc1, 0x34, 0xe6, 0xe6, 0x2e, 0xec, 0x14, 0xb3, 0x94, 0xd0, 0x3e, 0x3c,
	0xdd, 0xa8, 0xb6, 0x86, 0x7b, 0x3f, 0x82, 0xe6, 0x50, 0x92, 0x72, 0x93, 0x12, 0x8e, 0x3e, 0x83,
	0x36, 0xa3, 0x71, 0x30, 0xe3, 0x61, 0x44, 0x19, 0x27, 0xd1, 0x4a, 0x52, 0xa7, 0xe2, 0x27, 0x02,
	0xf5, 0xd6, 0x20, 0xfa, 0x1c, 0x76, 0x18, 0x27, 0x29, 0xdf, 0x88, 0xab, 0xc8, 0xb8, 0xb6, 0x84,
	0xcb, 0xc0, 0xde, 0x1f, 0x0a, 0x68, 0x0e, 0x89, 0x03, 0x76, 0x4d, 0x16, 0x14, 0x7d, 0x03, 0x07,
	0x7e, 0x12, 0x45, 0x59, 0x1c, 0xfa, 0x84, 0x8b, 0x3d, 0xd0, 0xd8, 0x4f, 0x82, 0x30, 0xbe, 0x92,
	0x5d, 0x34, 0x67, 0x0b, 0xef, 0xdf, 0xf1, 0xdb, 0x85, 0x1b, 0xed, 0x41, 0x8d, 0x51, 0x1a, 0x30,
	0xd9, 0xa5, 0x85, 0x73, 0x03, 0x05, 0x70, 0xc0, 0xb2, 0xd5, 0x2a, 0x49, 0x39, 0x0d, 0x66, 0x1b,
	0xa3, 0xb1, 0xe2, 0xd8, 0xfe, 0x1b, 0xdb, 0x78, 0xbf, 0x2c, 0xb6, 0x81, 0x32, 0xb3, 0x0b, 0xcf,
	0x1f, 0xde, 0x74, 0xc9, 0xe0, 0xef, 0x15, 0x00, 0x6b, 0x19, 0xd2, 0x98, 0x1b, 0x19, 0xbf, 0x46,
	0x87, 0xd0, 0xc8, 0x18, 0x4d, 0x63, 0x12, 0xd1, 0x7c, 0x2e, 0x5c, 0xda, 0xc2, 0xb7, 0x22, 0x8c,
	0xbd, 0x4f, 0xd2, 0xa0, 0x98, 0xa5, 0xb4, 0xd1, 0x09, 0xe8, 0x31, 0xe5, 0xb3, 0x94, 0x92, 0x9c,
	0xff, 0x24, 0xe3, 0x72, 0x10, 0x21, 0xdc, 0x76, 0x4c, 0x39, 0xa6, 0x44, 0x1e, 0x41, 0x92, 0x71,
	0xf4, 0x0a, 0x76, 0x45, 0xec, 0xfb, 0x34, 0xe4, 0xb4, 0x0c, 0xae, 0x16, 0x2a, 0xde, 0x89, 0x29,
	0x7f, 0x23, 0x3c, 0xeb, 0xe8, 0x2e, 0x34, 0x03, 0xca, 0x78, 0x18, 0xcb, 0x01, 0xa4, 0x7e, 0x34,
	0xbc, 0x09, 0xa1, 0x23, 0xd0, 0x7c, 0x39, 0xc1, 0x2c, 0x0c, 0x3a, 0xdb, 0xf9, 0xa6, 0x73, 0x60,
	0x10, 0xa0, 0x03, 0xd8, 0x7e, 0x1b, 0x2e, 0x39, 0x4d, 0x3b, 0x75, 0xe9, 0x29, 0xac, 0x87, 0x54,
	0xd0, 0x78, 0x48, 0x05, 0xe6, 0x21, 0x74, 0xee, 0x4f, 0x56, 0xaa, 0xf2, 0x08, 0x9e, 0xfd, 0x63,
	0x92, 0x92, 0x59, 0x02, 0xaa, 0xe1, 0x2f, 0xd0, 0x0b, 0x00, 0x9a, 0xa6, 0x49, 0x3a, 0xf3, 0x93,
	0x80, 0x96, 0x97, 0x59, 0x93, 0x98, 0x95, 0x04, 0x14, 0xbd, 0x84, 0x27, 0x79, 0x40, 0x44, 0x19,
	0x23, 0x57, 0x54, 0x72, 0xab, 0xe1, 0x96, 0x04, 0x2f, 0x72, 0xcc, 0xdc, 0x03, 0x74, 0x5b, 0xa5,
	0x6c, 0x41, 0x41, 0x2b, 0xce, 0xce, 0x5f, 0xdc, 0x27, 0x4a, 0x79, 0x84, 0xa8, 0xca, 0x3d, 0xa2,
	0x9e, 0x41, 0x63, 0x4e, 0xb8, 0x7f, 0x2d, 0x7c, 0xaa, 0x64, 0xa2, 0x2e, 0xed, 0x41, 0xd0, 0xfb,
	0x09, 0x54, 0x37, 0x9b, 0x7f, 0x6c, 0x83, 0x7f, 0x39, 0x89, 0xde, 0xcf, 0x50, 0x9b, 0xc6, 0xec,
	0xd3, 0xd5, 0xff, 0x4b, 0x01, 0xf5, 0x8c, 0xf2, 0x8f, 0x2d, 0xff, 0x7f, 0x80, 0xb7, 0x54, 0xf0,
	0xc3, 0xc2, 0x0f, 0xf9, 0xdb, 0x5a, 0xc3, 0x9a, 0x44, 0xdc, 0xf0, 0x83, 0xb8, 0x1c, 0xf5, 0x4d,
	0x29, 0xab, 0xce, 0x16, 0x5e, 0x03, 0x68, 0x0f, 0xaa, 0x59, 0x1c, 0x72, 0xa9, 0x5d, 0xa1, 0x71,
	0x69, 0xa1, 0x23, 0x68, 0x90, 0x8c, 0x27, 0x33, 0xe2, 0x2f, 0xa4, 0x6a, 0x1b, 0x4e, 0x05, 0xd7,
	0x05, 0x62, 0xf8, 0x0b, 0xf1, 0x04, 0xde, 0x17, 0x5b, 0x1b, 0x5a, 0x22, 0xaf, 0xb4, 0x11, 0xe8,
	0xeb, 0xfc, 0x52, 0x10, 0x06, 0x34, 0x0a, 0xc5, 0xb0, 0x3b, 0x07, 0xaa, 0xdc, 0x39, 0x50, 0x71,
	0x93, 0x0b, 0xb1, 0x89, 0x57, 0x49, 0x15, 0x37, 0x79, 0x6d, 0xf7, 0x7e, 0x81, 0xea, 0x69, 0x16,
	0xad, 0x50, 0x07, 0xea, 0xef, 0x92, 0x2c, 0x8d, 0xc9, 0xb2, 0xa0, 0x6a, 0x6d, 0xca, 0x77, 0x20,
	0x61, 0x21, 0x5f, 0x7f, 0x7c, 0x54, 0x5c, 0xda, 0xe8, 0x39, 0x68, 0xb7, 0x17, 0x4a, 0x2d, 0x88,
	0xb8, 0x85, 0xcc, 0xa7, 0xb0, 0x5b, 0x1a, 0xe5, 0xae, 0xdf, 0x41, 0x3b, 0x97, 0x31, 0x4e, 0x96,
	0xcb, 0x39, 0xf9, 0x94, 0x5a, 0x3e, 0x99, 0x42, 0x73, 0xe3, 0x85, 0x44, 0x2f, 0xe0, 0xc8, 0x1a,
	0x5f, 0x4c, 0xb0, 0xed, 0xba, 0x83, 0xf1, 0x48, 0x2c, 0x0d, 0x6f, 0x60, 0x0e, 0xed, 0x09, 0x1e,
	0x7b, 0xe3, 0xd7, 0xfa, 0x16, 0x6a, 0x40, 0x75, 0x34, 0x1e, 0xd9, 0xba, 0x22, 0x56, 0x97, 0xc3,
	0x81, 0xa9, 0x57, 0xc4, 0xea, 0xec, 0x72, 0x30, 0xd1, 0x55, 0x54, 0x07, 0x75, 0x78, 0xf9, 0x9d,
	0x5e, 0x3d, 0xf9, 0x53, 0x01, 0xb8, 0xfd, 0x8c, 0x8a, 0xb2, 0x13, 0xc3, 0x3a, 0x37, 0xce, 0x6c,
	0xef, 0x87, 0x89, 0xfd, 0x40, 0xd9, 0x27, 0xa0, 0x39, 0xc6, 0xe8, 0xd4, 0x75, 0x8c, 0x73, 0x51,
	0xbb, 0x03, 0x7b, 0xd6, 0x70, 0x60, 0x8f, 0x3c, 0x63, 0xea, 0x39, 0xf6, 0xc8, 0x1b, 0x58, 0x86,
	0x37, 0x18, 0x8f, 0xf4, 0x8a, 0xe8, 0x60, 0x58, 0xe7, 0xba, 0x8a, 0x74, 0x68, 0xb9, 0x53, 0xd3,
	0xb5, 0xf0, 0x60, 0x22, 0x5d, 0x55, 0x84, 0xa0, 0x3d, 0x1d, 0xdd, 0xc1, 0x6a, 0x22, 0xfc, 0xcc,
	0xf6, 0xf4, 0x6d, 0xd4, 0x82, 0xc6, 0x85, 0xed, 0xba, 0xc6, 0x99, 0xed, 0xea, 0x75, 0xd1, 0xae,
	0xa8, 0x6f, 0x9d, 0xeb, 0x0d, 0xe1, 0x74, 0x9d, 0xa9, 0x77, 0x3a, 0x7e, 0x33, 0xd2, 0x35, 0x31,
	0xce, 0xe9, 0xf4, 0x62, 0xa2, 0x83, 0xdc, 0x95, 0x6d, 0x60, 0xcf, 0xb4, 0x0d, 0x4f, 0x6f, 0x8a,
	0x06, 0x79, 0x16, 0x1e, 0x0f, 0x87, 0xa6, 0x48, 0x6d, 0x99, 0x5f, 0xc1, 0xa3, 0x3f, 0x33, 0x66,
	0x33, 0xff, 0x07, 0x92, 0x74, 0x38, 0xca, 0x7c, 0x5b, 0x3a, 0xbe, 0xfe, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x9a, 0x56, 0xea, 0x7b, 0x24, 0x09, 0x00, 0x00,
}
